from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages
from langchain_core.documents import Document


class State(TypedDict):
    """
    Define the state object for the chatbot.
    This can be extended with more fields as needed.
    """

    messages: Annotated[list, add_messages]
    retrieved_context: list[Document]
    final_response: str  # Final answer generated by the agent
    agent_cards: dict[
        str, str
    ]  # Store agent cards for sub-agents (technical, fundamental, news)
    synthesizer_feedback: str  # feedback from synthesizer to planner about any missing information or gaps in the response
    iteration_count: (
        int  # Track number of planner-tool-synthesizer loops to prevent infinite loops
    )
