from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages
from langchain_core.documents import Document


# Define the state structure for the advisor agent workflow
class State(TypedDict):
    messages: Annotated[list, add_messages]
    final_response: str  # Final answer generated by the agent
    # Store agent cards for sub-agents (technical, fundamental, news)
    agent_cards: dict[str, str]
    iteration_count: int  # Track number of loops to prevent infinite loops
    # Flag to indicate if max iteration limit was hit in the planner-synthesizer loop
    max_iteration_hit: bool = False
    # Flag to indicate if the synthesizer response is complete or not
    response_complete: bool = False
