from typing import TypedDict, Annotated
from langgraph.graph.message import add_messages
from langchain_core.documents import Document


class State(TypedDict):
    """
    Define the state object for the chatbot.
    This can be extended with more fields as needed.
    """

    messages: Annotated[list, add_messages]
    retrieved_context: list[Document]
    intent: str  # Classified intent: "needs_rag" or "no_rag"
    rag_context_used: bool = False  # flag to track rag usage
    final_response: str  # Final answer generated by the agent
    tool_outputs: str  # Store outputs from any tools used during the workflow
    current_topic_summary: str  # summary of messages, older than a threshold, in state - to help keep small context but not lose information when topic is same for long time
    previous_topic_summary: str  #  summary of the previous topic - when user switches topics. Kept to help with comparisions between topics.
